# ansible/inventory/aws.yml
# Đây là file inventory động, sử dụng plugin aws_ec2 của Ansible.

plugin: amazon.aws.aws_ec2
regions:
  - ap-southeast-1 # Thay bằng region của bạn

# Lọc các instance đang chạy
filters:
  instance-state-name: running
# Gom nhóm các host dựa trên tag "Project"
keyed_groups:
  - key: tags.Project
    prefix: tag_Project_