# kubernetes/base/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app # Phải khớp với label của Pod trong deployment.yaml
  ports:
    - protocol: TCP
      port: 80 # Cổng mà các service khác sẽ gọi vào
      targetPort: 8080 # Cổng containerPort trong deployment.yaml